spring.application.name=bakong-api-integration

# Set the active profile to 'dev' for development environment
# You can change this to 'prod' for production environment
spring.profiles.active=dev

# BAKONG
bakong.account-id=${BAKONG_ACCOUNT_ID}
bakong.acquiring-bank=${ACQUIRINGBANK}
bakong.merchant-name=${MERCHANTNAME}
bakong.mobile-number=${MOBILENUMBERSTORELABEL}
bakong.store-label=${STORELABEL}
bakong.base-url=${BAKONG_BASE_URL}
bakong.email=${EMAIL}